<?php

	if ($anoActual =='2015') {
		if ($mesActual =='11') {
			$calendarConf = array('0','1','7','8','14','15','21','22','28','29','30','0','0','5');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='12') {
			$calendarConf = array('2','1','5','6','12','13','19','20','26','27','31','0','0','2');
			include('home.v.calendar.temp.phtml');
		}
	}

	else if ($anoActual =='2016') {
		if ($mesActual =='01') {
			$calendarConf = array('5','1','2','3','9','10','16','17','23','24','30','31','31','6');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='02') {
			$calendarConf = array('1','1','6','7','13','14','20','21','27','28','29','0','0','5');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='03') {
			$calendarConf = array('2','1','5','6','12','13','19','20','26','27','31','0','0','2');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='04') {
			$calendarConf = array('5','1','2','3','9','10','16','17','23','24','30','0','0','0');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='05') {
			$calendarConf = array('0','1','7','8','14','15','21','22','28','29','31','0','0','4');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='06') {
			$calendarConf = array('3','1','4','5','11','12','18','19','25','26','30','0','0','2');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='07') {
			$calendarConf = array('5','1','2','3','9','10','16','17','23','24','30','31','31','6');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='08') {
			$calendarConf = array('1','1','6','7','13','14','20','21','27','28','31','0','0','3');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='09') {
			$calendarConf = array('4','1','3','4','10','11','17','18','24','25','30','0','0','1');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='10') {
			$calendarConf = array('6','1','1','2','8','9','15','16','22','23','29','30','31','5');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='11') {
			$calendarConf = array('2','1','5','6','12','13','19','20','26','27','30','0','0','3');
			include('home.v.calendar.temp.phtml');
		}
		else if ($mesActual =='12') {
			$calendarConf = array('4','1','3','4','10','11','17','18','24','25','31','0','0','0');
			include('home.v.calendar.temp.phtml');
		}
	}

	else {

	}
?>
